baseurl = "https://geekcampsg.github.io/"
languageCode = "en-us"
title = "Geekcamp Singapore 2018+"
# https://github.com/jrutheiser/hugo-lithium-theme.git
theme = "pacgeek"
googleAnalytics = ""
disqusShortname = ""

[params]
    description = "By geeks. For geeks."

    [params.logo]
    url = "logo.png"
    width = 60
    height = 60
    alt = "logo"
